# All kind of configuration goes here
# See the guide
# https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customization.html

proxy:
  secretToken: "YOUR HEX TOKEN"
  https:
    enabled: false

auth:
  type: dummy
  dummy:
    password: 'supersecretpassword!'
  whitelist:
    users:
      - admin

singleuser:
  storage:
    capacity: 4Gi
    dynamic:
      storageClass: gp2
