proxy:
  secretToken: "YOUR HEX TOKEN HERE"
  https:
    enabled: false

auth:
  type: dummy
  dummy:
    password: 'supersecretpassword!'
  whitelist:
    users:
      - admin

singleuser:

  memory:
    limit: 500M
    guarantee: 500M

  storage:
    extraVolumes:
      - name: mntdatas3fs
        hostPath:
          path: /mnt/s3data
    extraVolumeMounts:
      - name: mntdatas3fs
        mountPath: /home/jovyan/shared

  extraEnv:
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
  uid: 0
  cmd: start-singleuser.sh
